Update Dockerfile to install python3-dev instead of python-dev
Currently the build is failing because of this:

```
ERROR: unsatisfiable constraints:
  python-dev (missing):
    required by: world[python-dev]
The command '/bin/sh -c apk add --no-cache     libffi     libffi-dev     python-dev     build-base     && pip --no-cache-dir install cffi /var/cache/napalm-logs/     && rm -rf /var/cache/napalm-logs/' returned a non-zero code: 1
```